name: Mirror to GitLab

on:
  push:
    branches: [ master, development ] # Add other branches if you use them
  delete:

jobs:
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Mirror to GitLab
        uses: yesolutions/mirror-action@662fce0eced8996f64d7fa264d76cddd84827f33 # master @ 2025-08-11
        with:
          REMOTE: "https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/Salgaar/arx-runa.git"
          GIT_PUSH_ARGS: "--tags --force"